name: Deploy Nuxt.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Настройка SSH (для деплоя на сервер)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEVUSER }}

      # Шаг 3: Деплой на сервер
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no devuser@185.117.155.59 << 'EOF'
            # Перейти в директорию с проектом
            cd /home/devuser/gagent

            # Забрать последние изменения
            git pull origin main

            # Установить зависимости
            /run/user/1000/fnm_multishells/28367_1744644707457/bin/npm install

            # Собрать проект
            /run/user/1000/fnm_multishells/28367_1744644707457/bin/npm run build

            # Перезапустить Nuxt.js (если используете PM2)
            /run/user/1000/fnm_multishells/28367_1744644707457/bin/pm2 restart nuxt-app || /run/user/1000/fnm_multishells/28367_1744644707457/bin/pm2 start npm --name "nuxt-app" -- run start
          EOF
