name: Deploy Nuxt.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Настройка SSH (для деплоя на сервер)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEVUSER }}

      # Шаг 3: Установить зависимости на сервере
      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no devuser@185.117.155.59 << 'EOF'
            cd /home/devuser/gagent
            git reset --hard
            git pull origin main
            npm install # Установить все зависимости, включая Tailwind CSS
          EOF

      # Шаг 4: Собрать проект
      - name: Build the project
        run: |
          ssh -o StrictHostKeyChecking=no devuser@185.117.155.59 << 'EOF'
            cd /home/devuser/gagent
            npm run build # Собрать проект
          EOF

      # Шаг 5: Перезапустить приложение (если используется PM2)
      - name: Restart Nuxt.js App
        run: |
          ssh -o StrictHostKeyChecking=no devuser@185.117.155.59 << 'EOF'
            cd /home/devuser/gagent
            pm2 restart nuxt-app || pm2 start npm --name "nuxt-app" -- run start
          EOF
